name: SageMaker Sentiment Analysis CI/CD - Development

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 sagemaker pandas wget s3fs python-dotenv scikit-learn numpy nltk beautifulsoup4 html5lib tabulate

      - name: Install CML
        run: |
          npm install -g @dvcorg/cml

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names my-app --region $AWS_REGION || \
          aws ecr create-repository --repository-name my-app --region $AWS_REGION
        env:
          AWS_REGION: ap-southeast-1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: my-app
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG    

      - name: Train model
        env:
          PREFIX: ${{ secrets.PREFIX }}
          GITHUB_SHA: ${{ github.sha }}
          AWS_DEFAULT_REGION: ap-southeast-1
          IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        run: |
          cd Project
          python train_job.py
          cat details.txt >> report.md

      - name: Comment report to PR
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd Project
          cml-send-comment report.md
